apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: joindevoppsiva
  region: us-east-1

managedNodeGroups:
- name: joindevopss
  instanceType: m5.large
  desiredCapacity: 3
  spot: true
